### ISSUE TITLE
android-5.1.1_r38

### ISSUE THREAD

**Issue by arizaini** [omnirom/android#14]
@humberos request for update lolipop sir?

**Comment by humberos** [comment]
Hi @arizaini 
Unfortunately due to a limited disk space (my computer) I do not have L sources.
So I am really sorry but I can't do this for now.

**Comment by arizaini** [comment]
ahh ok, do u know who's manage lolipop source?

**Comment by humberos** [comment]
@arizaini 
I don't think so. But I will talk about it with the Omni team.
To be honest I'd say "no hope for this task".
Although we have a good team but they are working on Nougat version and also they are fixing some things on M yet.

**Comment by skinzor** [comment]
@humberos The upgrade cant be done by changing _r28 to _r37 or _38 like here:  https://github.com/omnirom/android/commit/992b51b9b8ba45e16fcc9c80cbd6765390d84daf ?

**Comment by humberos** [comment]
@skinzor 
No love for 5.1 since I have no space enough in my hdd.
I am sorry and happy new 2017!

**Comment by skinzor** [comment]
@humberos You didnt get me :D I asked if revision can be updated to _r37 by doing this:  https://github.com/skinzor/android/commit/1f14cd7ea69ff3d80c04126a5dc772f0664105b0 .

Happy new year you too!

**Comment by humberos** [comment]
@skinzor Oh, sorry.
This change will update only the manifest for pure AOSP repos.
It is no so simple since Omni has so many forked projects from AOSP then they will need some love to match with that change. I mean those projects will need to get merged with this tag too.

**Comment by skinzor** [comment]
@humberos Thank you for your reply! I just have been told on the omni freenode that i should use the scripts from vendor/omni/utils/. I will try if i manage to build omni as it is now.

Once again, thank you!
Have a nice day!
