### ISSUE TITLE
could not find your device folder location

### ISSUE THREAD

**Issue by husnoo** [omnirom/android#27]
Hi,
I downloaded omnirom like follows, which downloaded 70 GB of files. Now I'm trying to build it, but there's an error about the device being missing - I'm trying to build for the emulator. I'm following the instructions from here: https://github.com/omnirom/android

```
cd ~
mkdir omni
cd omni
repo init -u git://github.com/omnirom/android.git -b android-9.0
repo sync
source build/envsetup.sh
lunch # shows omni_emulator-userdebug
brunch omni_emulator-userdebug
```
The error is
```
~/omni$ brunch omni_emulator-userdebug
Your device can't be found in device sources..
Traceback (most recent call last):
  File "vendor/omni/build/tools/roomservice.py", line 356, in <module>
    fetch_dependencies(device)
  File "vendor/omni/build/tools/roomservice.py", line 305, in fetch_dependencies
    raise Exception("ERROR: could not find your device "
Exception: ERROR: could not find your device folder location, bailing out

============================================
```
Hopefully this isn't too hard to fix? Happy to send a pull request if somebody can explain how to fix it.

thanks!

**Comment by Bi3g0** [comment]
I have same problem， did you have resolved it？

**Comment by Tarikkassy** [comment]
i have same problem

**Comment by darkobas** [comment]
mkdir device/{vendor} first

**Comment by SueHeir** [comment]
I am having the same problem, what is {vendor} ?

**Comment by MartinX3** [comment]
@SueHeir it is just a variabe
device/sony
device/huawai
etc.
