### ISSUE TITLE
get error on compiling 

### ISSUE THREAD

**Issue by Sudhanshu-Gairola** [omnirom/android#32]
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ3A.190605.003
OUT_DIR=/home/gairola_gg/omni/out
============================================
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=9
TARGET_PRODUCT=omni_vince
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm64
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=cortex-a53
TARGET_2ND_ARCH=arm
TARGET_2ND_ARCH_VARIANT=armv8-a
TARGET_2ND_CPU_VARIANT=cortex-a53
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.15.0-1033-gcp-x86_64-Ubuntu-18.04.2-LTS
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=PQ3A.190605.003
OUT_DIR=/home/gairola_gg/omni/out
============================================
[1/1] /home/gairola_gg/omni/out/soong/.minibootstrap/min...p /home/gairola_gg/omni/out/soong/.bootstrap/build.ninja
[1/1] /home/gairola_gg/omni/out/soong/.bootstrap/bin/soong_build /home/gairola_gg/omni/out/soong/build.ninja
FAILED: /home/gairola_gg/omni/out/soong/build.ninja 
/home/gairola_gg/omni/out/soong/.bootstrap/bin/soong_build -t -l /home/gairola_gg/omni/out/.module_paths/Android.bp.list -b /home/gairola_gg/omni/out/soong -n /home/gairola_gg/omni/out -d /home/gairola_gg/omni/out/soong/build.ninja.d -o /home/gairola_gg/omni/out/soong/build.ninja Android.bp
error: build/soong/Android.bp:365:20: unrecognized property "additional_deps"
ninja: build stopped: subcommand failed.
03:52:06 soong bootstrap failed with: exit status 1

#### failed to build some targets (1 seconds) ####

real    0m1.300s
user    0m4.631s
sys     0m1.519s
gairola_gg@instance-1:~/omni$

**Comment by darkobas** [comment]
problem doesnt match source

**Comment by Sudhanshu-Gairola** [comment]
That is source problem many developer told me
