### ISSUE TITLE
Modification request: Add branch 9.1

### ISSUE THREAD

**Issue by TanyaEleventhGoddess** [omnirom/android#34]
Android 9.1 is generally better than android 9.0, adds more settings and enables again advanced reboot

It would be nice using it as source for builds, and I'm quite sure that modifications needed for bumping from android 9.0 are not very much

**Comment by TanyaEleventhGoddess** [comment]
How rude, at least explain me why it isn't necessary

**Comment by MartinX3** [comment]
There is no 9.1
Next version is 10.0
And each android version has its own branch

**Comment by TanyaEleventhGoddess** [comment]
Sorry, I got confused by a wrong memory of this:

https://www.reddit.com/r/oneplus/comments/9tigux/they_brought_back_advanced_reboot_on_902/

Is advanced reboot available in android 9 omnirom?

**Comment by MartinX3** [comment]
Woops

For sure :)

**Comment by TanyaEleventhGoddess** [comment]
Nice to hear, in HavocOS 2.7 it isn't :)

**Comment by darkobas** [comment]
This is not a chat/forum
