### ISSUE TITLE
Support for Umidigi devices?

### ISSUE THREAD

**Issue by sacrophyte** [omnirom/android#49]
Good day! Curious if anyone has knowledge of Umidigi devices (eg, A9). I have not yet found the Omnirom has a download for Umidigi, so I am asking around.

**Comment by Entropy512** [comment]
First:  Omni does not track issues on github.

Second:  You can safely assume that most noname low-cost Chinese phones have Mediatek SoCs, and it's unlikely an MTK device will ever be supported by any opensource project.  I did Google the A9 and it's a Mediatek.
